---
- hosts: localhost
  gather_facts: no
  become: true
  tasks:

  - name: ADD USER
    user:
      name: user1
      password: "{{ user_pass | password_hash('sha512') }}"
      shell: /bin/bash
      groups: sudo
      append: yes

  - name: COPY pub ssh key to ~user1/.ssh/id_rsa
    copy:
      src: /etc/ansible/id_rsa.pub
      dest: /home/user1/.ssh/id_rsa
      remote_src: yes

  - name: SET authorized key 
    authorized_key:
      user: user1
      state: present
      key: "{{ lookup('file', '/home/user1/.ssh/id_rsa.pub') }}"
